# Generated by Django 5.2.17 on 2026-09-30 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='audit_actor_required_unless_system',
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_kind', 'user'), _negated=True), ('actor__isnull', False), _connector='OR'), name='audit_user_action_has_actor'),
        ),
    ]
