# Generated by Django 5.2.17 on 2026-09-30 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0002_remove_auditevent_audit_actor_required_unless_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='audit_user_action_has_actor',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Renseigne actor_public_id des événements existants avant de poser la contrainte.
        migrations.RunSQL(
            sql="""
                UPDATE trust_auditevent AS a SET actor_public_id = u.public_id
                FROM accounts_user AS u WHERE a.actor_id = u.id AND a.actor_public_id IS NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_kind', 'user'), _negated=True), ('actor_public_id__isnull', False), _connector='OR'), name='audit_user_action_has_actor_id'),
        ),
    ]
