# Generated by Django 5.2.17 on 2026-10-03 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_bookingphoto_options'),
        ('trust', '0004_append_only_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('not_done', 'Travail non fait'), ('poor_quality', 'Mauvaise qualité'), ('damage', 'Dégât'), ('price', 'Prix'), ('behaviour', 'Comportement'), ('other', 'Autre')], max_length=12)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Tranché')], default='open', max_length=8)),
                ('decision', models.CharField(blank=True, choices=[('for_client', 'En faveur du client'), ('for_pro', 'En faveur du pro'), ('no_fault', 'Sans faute')], max_length=10)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='bookings.booking')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'litige',
                'ordering': ('-created_at',),
                'permissions': [('decide_dispute', 'Médiation : trancher un litige')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('decision', ''), ('status', 'open')), models.Q(('status', 'resolved'), models.Q(('decision', ''), _negated=True)), _connector='OR'), name='dispute_decision_iff_resolved')],
            },
        ),
    ]
