# Generated by Django 5.2.17 on 2026-10-03 01:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', code='slug_invalid')])),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'ville',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='city_slug_format')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.CharField(help_text="Identifiant de l'URL (/plombier/ouakam). Figé après création.", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', code='slug_invalid')])),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Séparés par des virgules : « frigoriste, clim ».', size=None)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='centre')),
                ('radius_m', models.PositiveIntegerField(default=1500, verbose_name='rayon (m)')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Optionnel ; prime sur le cercle.', null=True, srid=4326, verbose_name='contour')),
                ('position', models.PositiveSmallIntegerField(default=100, help_text='Popularité : 1 en tête.')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='zones.city')),
                ('trades', models.ManyToManyField(blank=True, related_name='zones', to='catalog.trade', verbose_name='métiers ouverts')),
            ],
            options={
                'verbose_name': 'zone',
                'ordering': ('position', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='zone_slug_format'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='zone_name_required'), models.CheckConstraint(condition=models.Q(('radius_m__gte', 200), ('radius_m__lte', 15000)), name='zone_radius_bounds')],
            },
        ),
    ]
