# Generated by Django 5.2.17 on 2026-10-03 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('zones', '0002_catalog_entry_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=60, verbose_name='nom commercial')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('suspended', 'Suspendu')], default='pending', max_length=10)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('masked_numbers_count', models.PositiveIntegerField(default=0, verbose_name='numéros masqués')),
                ('is_demo', models.BooleanField(default=False, verbose_name='démo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to=settings.AUTH_USER_MODEL)),
                ('trades', models.ManyToManyField(blank=True, related_name='providers', to='catalog.trade')),
                ('zones', models.ManyToManyField(blank=True, related_name='providers', to='zones.zone')),
            ],
            options={
                'verbose_name': 'pro',
                'ordering': ('-created_at',),
                'permissions': [('verify_provider', 'Pros : vérifier ou suspendre une fiche')],
                'constraints': [models.UniqueConstraint(fields=('owner',), name='provider_one_per_owner'), models.CheckConstraint(condition=models.Q(('business_name', ''), _negated=True), name='provider_business_name_required')],
            },
        ),
    ]
