# Generated by Django 5.2.17 on 2026-09-30 12:50

import django.db.models.deletion
import jeflink.accounts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_changed_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=2)),
                ('profile_status', models.CharField(choices=[('guest', 'Invité'), ('complete', 'Complet')], default='guest', max_length=8)),
                ('terms_version', models.CharField(blank=True, max_length=16)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('fraud', 'Fraude'), ('user_request', "Demande de l'utilisateur"), ('ops_other', 'Autre (Ops)')], max_length=16)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_review_account', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('ops_accounts_view', 'Ops : consulter les comptes'), ('ops_accounts_manage', 'Ops : gérer les comptes (sessions, blocages, état)'), ('ops_accounts_change_phone', "Ops : changer le numéro d'un compte")],
            },
            managers=[
                ('objects', jeflink.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Prestataire (gérant)'), ('technician', 'Technicien'), ('ops', 'Équipe Jeflink')], max_length=16)),
                ('reason_code', models.CharField(max_length=32)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', True), ('phone__regex', '^\\+[1-9][0-9]{7,14}$'), _connector='OR'), name='user_phone_e164'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('deleted_at__isnull', False), _connector='OR'), name='user_phone_required_unless_deleted'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile_status', 'complete'), _negated=True), models.Q(('display_name', ''), _negated=True), _connector='OR'), name='user_complete_requires_display_name'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='rolegrant_one_active_per_role'),
        ),
    ]
