# Generated by Django 5.2.17 on 2026-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_deactivated_by_user_user_inactive_has_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpPhoneBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hmac', models.CharField(max_length=64, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
