# Generated by Django 5.2.17 on 2026-09-30 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpphoneblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(choices=[('client', 'App client'), ('pro', 'App Pro'), ('web', 'Web'), ('console', 'Console')], max_length=8)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=8)),
                ('device_label', models.CharField(blank=True, max_length=60)),
                ('install_id', models.CharField(blank=True, max_length=64)),
                ('refresh_hash', models.CharField(max_length=64, unique=True)),
                ('previous_refresh_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('grace_used_at', models.DateTimeField(blank=True, null=True)),
                ('auth_time', models.DateTimeField()),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('restricted', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField()),
                ('idle_expires_at', models.DateTimeField()),
                ('absolute_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('logout', 'Déconnexion'), ('user_revoked', "Révoquée par l'utilisateur"), ('ops_revoked', "Révoquée par l'Ops"), ('reuse_detected', 'Réutilisation de refresh'), ('limit', 'Trop de sessions'), ('replaced', 'Remplacée sur le même appareil'), ('phone_changed', 'Numéro changé'), ('account_deleted', 'Compte supprimé'), ('account_disabled', 'Compte désactivé'), ('ops_role_changed', 'Rôle ops modifié')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetiredRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_hash', models.CharField(max_length=64, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.devicesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', 'revoked_at'], name='accounts_de_user_id_45e55c_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicesession',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), models.Q(('revoked_reason', ''), _negated=True), _connector='OR'), name='devicesession_revoked_has_reason'),
        ),
    ]
