# Generated by Django 5.2.17 on 2026-09-30 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dormant_and_session_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=2)),
                ('purpose', models.CharField(choices=[('login', 'Connexion'), ('delete_account', 'Suppression du compte'), ('change_phone', 'Changement de numéro'), ('sensitive_action', 'Action sensible')], max_length=16)),
                ('challenge_secret_hash', models.CharField(max_length=64)),
                ('app', models.CharField(choices=[('client', 'App client'), ('pro', 'App Pro'), ('web', 'Web'), ('console', 'Console')], max_length=8)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('locked', 'Verrouillé'), ('expired', 'Expiré')], default='pending', max_length=8)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_install_id', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.devicesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtpDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('voice', 'Appel vocal')], default='sms', max_length=8)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('unknown', 'Issue inconnue')], default='queued', max_length=8)),
                ('gateway', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('segments', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.otpchallenge')),
            ],
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['phone', 'created_at'], name='accounts_ot_phone_937832_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('failed_attempts__lte', 5)), name='otpchallenge_max_attempts'),
        ),
        migrations.AddConstraint(
            model_name='otpdelivery',
            constraint=models.UniqueConstraint(fields=('challenge', 'attempt_no'), name='otpdelivery_unique_attempt'),
        ),
        migrations.AddConstraint(
            model_name='otpdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_no__gte', 1), ('attempt_no__lte', 3)), name='otpdelivery_attempt_range'),
        ),
    ]
