# Generated by Django 5.2.17 on 2026-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpchallenge_otpdelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdelivery',
            name='status',
            field=models.CharField(choices=[('queued', 'En file'), ('sending', 'Envoi en cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('unknown', 'Issue inconnue')], default='queued', max_length=8),
        ),
        migrations.AddIndex(
            model_name='otpdelivery',
            index=models.Index(fields=['created_at'], name='accounts_ot_created_2d7ab4_idx'),
        ),
    ]
