# Generated by Django 5.2.17 on 2026-09-30 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpdelivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('invitation', 'Invitation')], max_length=16)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('phone_hmac', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=2)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sending', 'Envoi en cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('unknown', 'Issue inconnue')], default='queued', max_length=8)),
                ('gateway', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('segments', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='accounts_no_created_16bbea_idx'), models.Index(fields=['phone_hmac', 'created_at'], name='accounts_no_phone_h_9f3214_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('role', models.CharField(choices=[('owner', 'Prestataire (gérant)'), ('technician', 'Technicien'), ('ops', 'Équipe Jeflink')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=8)),
                ('display_name_hint', models.CharField(blank=True, max_length=80)),
                ('context_ref', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'status'], name='accounts_ro_phone_013ebd_idx'), models.Index(fields=['invited_by', 'created_at'], name='accounts_ro_invited_91b85d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('phone', 'role', 'context_ref'), name='roleinvitation_one_pending'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'technician'])), name='roleinvitation_pro_role'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), ('phone__regex', '^\\+[1-9][0-9]{7,14}$')), models.Q(models.Q(('status', 'pending'), _negated=True), ('phone', '')), _connector='OR'), name='roleinvitation_phone_only_while_pending')],
            },
        ),
    ]
