# Generated by Django 5.2.17 on 2026-09-30 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitations_and_notice_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='revoked_reason',
            field=models.CharField(blank=True, choices=[('logout', 'Déconnexion'), ('user_revoked', "Révoquée par l'utilisateur"), ('ops_revoked', "Révoquée par l'Ops"), ('reuse_detected', 'Réutilisation de refresh'), ('limit', 'Trop de sessions'), ('replaced', 'Remplacée sur le même appareil'), ('phone_changed', 'Numéro changé'), ('account_deleted', 'Compte supprimé'), ('account_disabled', 'Compte désactivé'), ('ops_role_changed', 'Rôle ops modifié'), ('mfa_locked', 'Second facteur verrouillé'), ('mfa_reset', 'Second facteur réinitialisé')], max_length=20),
        ),
        migrations.CreateModel(
            name='OpsEnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_by_operator', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_encrypted', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(default=0)),
                ('recent_failures', models.JSONField(blank=True, default=list)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MfaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('app', models.CharField(choices=[('client', 'App client'), ('pro', 'App Pro'), ('web', 'Web'), ('console', 'Console')], max_length=8)),
                ('device_label', models.CharField(blank=True, max_length=60)),
                ('install_id', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.otpchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.opsenrollmenttoken')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('failed_attempts__lte', 5)), name='mfachallenge_max_attempts'), models.CheckConstraint(condition=models.Q(('app', 'console')), name='mfachallenge_console_only')],
            },
        ),
    ]
