# Generated by Django 5.2.17 on 2026-09-30 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_reveal_phone_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesms',
            name='kind',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('phone_changed', "Information à l'ancien numéro"), ('phone_change_req', 'Alerte : changement de numéro demandé')], max_length=16),
        ),
        migrations.CreateModel(
            name='PhoneChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_phone', models.CharField(blank=True, max_length=16)),
                ('new_phone_hmac', models.CharField(max_length=64)),
                ('requires_approval', models.BooleanField()),
                ('reason_code', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending_approval', "En attente d'approbation"), ('approved', 'Approuvée, code envoyé'), ('completed', 'Terminée'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='pending_approval', max_length=16)),
                ('codes_sent', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.otpchallenge')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='phonechange_second_operator'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['pending_approval', 'approved']), models.Q(('new_phone', ''), _negated=True)), models.Q(models.Q(('status__in', ['pending_approval', 'approved']), _negated=True), ('new_phone', '')), _connector='OR'), name='phonechange_new_phone_only_while_open'), models.CheckConstraint(condition=models.Q(('codes_sent__lte', 3)), name='phonechange_max_codes'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'approved'])), fields=('user',), name='phonechange_one_open_per_user'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'approved'])), fields=('new_phone',), name='phonechange_one_open_per_new_phone')],
            },
        ),
    ]
