# Generated by Django 5.2.17 on 2026-09-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_review_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaccess',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='revoked_reason',
            field=models.CharField(blank=True, choices=[('logout', 'Déconnexion'), ('user_revoked', "Révoquée par l'utilisateur"), ('ops_revoked', "Révoquée par l'Ops"), ('reuse_detected', 'Réutilisation de refresh'), ('limit', 'Trop de sessions'), ('replaced', 'Remplacée sur le même appareil'), ('phone_changed', 'Numéro changé'), ('account_deleted', 'Compte supprimé'), ('account_disabled', 'Compte désactivé'), ('ops_role_changed', 'Rôle ops modifié'), ('mfa_locked', 'Second facteur verrouillé'), ('mfa_reset', 'Second facteur réinitialisé'), ('review_ended', 'Fin de la revue des stores')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewaccess',
            name='code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
