# Generated by Django 5.2.17 on 2026-10-03 02:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnservedDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_slug', models.CharField(blank=True, max_length=50)),
                ('zone_slug', models.CharField(blank=True, max_length=50)),
                ('reason', models.CharField(max_length=24)),
                ('zone_text', models.CharField(blank=True, max_length=40)),
                ('nearest_zone_slug', models.CharField(blank=True, max_length=50)),
                ('distance_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('whatsapp', 'WhatsApp')], max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'demande non servie',
                'verbose_name_plural': 'demandes non servies',
                'ordering': ('-occurred_at',),
            },
        ),
    ]
