# Generated by Django 5.2.17 on 2026-10-03 02:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0002_validation_pros_group'),
        ('zones', '0002_catalog_entry_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_text', models.CharField(blank=True, max_length=40)),
                ('landmark', models.CharField(blank=True, max_length=300)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('urgent', models.BooleanField(default=False)),
                ('preferred_when', models.CharField(choices=[('asap', 'Dès que possible'), ('date', 'Un jour précis')], default='asap', max_length=4)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_period', models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi'), ('evening', 'Soir'), ('any', 'Peu importe')], default='any', max_length=9)),
                ('status', models.CharField(choices=[('needs_zone', 'Quartier à vérifier'), ('open', 'Ouverte'), ('quoted', 'Devis reçus'), ('booked', 'Réservée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('whatsapp', 'WhatsApp')], max_length=8)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('dispatch_rank', models.BigIntegerField(default=0)),
                ('first_quoted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=24)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('excluded_providers', models.ManyToManyField(blank=True, related_name='excluded_requests', to='providers.provider')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.trade')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='zones.zone')),
            ],
            options={
                'verbose_name': 'demande',
                'ordering': ('-created_at',),
                'permissions': [('attach_servicerequest', 'Demandes : rattacher à une zone')],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='requests_se_status_f067ac_idx'), models.Index(fields=['client', 'status'], name='requests_se_client__eedd7a_idx'), models.Index(fields=['status', 'dispatch_rank'], name='requests_se_status_816624_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'idempotency_key'), name='request_idempotency_per_client'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('needs_zone', 'open', 'quoted', 'booked')), _negated=True), models.Q(('landmark', ''), _negated=True), ('location__isnull', False), _connector='OR'), name='request_landmark_or_location'), models.CheckConstraint(condition=models.Q(('zone__isnull', False), ('status__in', ('needs_zone', 'cancelled')), _connector='OR'), name='request_zone_unless_needs_zone'), models.CheckConstraint(condition=models.Q(('preferred_when', 'asap'), ('preferred_date__isnull', False), _connector='OR'), name='request_date_when_date')],
            },
        ),
    ]
