# Generated by Django 5.2.17 on 2026-10-03 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_validation_pros_group'),
        ('requests', '0002_catalog_entry_attaches_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Envoyé'), ('held', 'En attente du choix du client'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('withdrawn', 'Retiré'), ('expired', 'Expiré')], default='submitted', max_length=10)),
                ('kind', models.CharField(choices=[('fixed', 'Prix ferme'), ('visit', 'Visite seulement')], max_length=5)),
                ('total_xof', models.PositiveBigIntegerField()),
                ('visit_deductible', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='providers.provider')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='requests.servicerequest')),
            ],
            options={
                'verbose_name': 'devis',
                'ordering': ('slot_start', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('labor', "Main-d'œuvre"), ('parts', 'Pièces'), ('travel', 'Déplacement'), ('other', 'Autre')], max_length=6)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('amount_xof', models.PositiveBigIntegerField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requests.quote')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['request', 'status'], name='requests_qu_request_ad80af_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['provider', 'status'], name='requests_qu_provide_c0313a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'valid_until'], name='requests_qu_status_743e64_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='quote_idempotency_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('submitted', 'held', 'accepted'))), fields=('request', 'provider'), name='quote_one_active_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('total_xof__gt', 0)), name='quote_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('slot_end__gt', models.F('slot_start'))), name='quote_slot_ordered'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'visit'), ('visit_deductible', False), _connector='OR'), name='quote_deductible_only_visit'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'position'), name='quoteline_position'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_xof__gt', 0)), name='quoteline_amount_positive'),
        ),
    ]
