# Generated by Django 5.2.17 on 2026-10-03 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0002_validation_pros_group'),
        ('requests', '0003_quotes'),
        ('zones', '0002_catalog_entry_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerequest',
            name='request_landmark_or_location',
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('needs_zone', 'open', 'quoted')), _negated=True), models.Q(('landmark', ''), _negated=True), ('location__isnull', False), _connector='OR'), name='request_landmark_or_location'),
        ),
    ]
