# Generated by Django 5.2.17 on 2026-10-05 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_mediation_cancel_group'),
        ('providers', '0002_validation_pros_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pro_commission_due', 'Commission due par le pro'), ('platform_revenue', 'Revenus de la plateforme'), ('platform_collections', 'Fonds reçus, à rapprocher'), ('platform_goodwill', 'Gestes commerciaux'), ('client_escrow', 'Séquestre client (V2)'), ('pro_pending', 'Gains du pro en attente (V2)'), ('pro_available', 'Gains du pro disponibles (V2)')], max_length=24)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='providers.provider')),
            ],
            options={
                'verbose_name': 'compte du grand livre',
                'verbose_name_plural': 'comptes du grand livre',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('commission', 'Commission'), ('settlement', 'Règlement'), ('reversal', 'Contre-passation'), ('goodwill_credit', 'Geste commercial'), ('correction_debit', 'Correction en faveur de Jeflink')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('reason_code', models.CharField(blank=True, max_length=24)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor_kind', models.CharField(choices=[('system', 'Système'), ('ops', 'Ops'), ('pro', 'Pro')], max_length=8)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bookings.booking')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='providers.provider')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='wallet.ledgertransaction')),
            ],
            options={
                'verbose_name': 'transaction du grand livre',
                'verbose_name_plural': 'transactions du grand livre',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=6)),
                ('amount_xof', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.ledgertransaction')),
            ],
            options={
                'verbose_name': 'ligne du grand livre',
                'verbose_name_plural': 'lignes du grand livre',
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('kind', 'provider'), name='ledgeraccount_unique_kind_provider', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['pro_available', 'pro_commission_due', 'pro_pending']), ('provider__isnull', False)), models.Q(models.Q(('kind__in', ['pro_available', 'pro_commission_due', 'pro_pending']), _negated=True), models.Q(('provider__isnull', False), _negated=True)), _connector='OR'), name='ledgeraccount_provider_iff_pro_kind'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'reversal'), ('reverses__isnull', False)), models.Q(models.Q(('kind', 'reversal'), _negated=True), models.Q(('reverses__isnull', False), _negated=True)), _connector='OR'), name='ledgertransaction_reverses_iff_reversal'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('actor_kind', 'system'), ('actor__isnull', False), _connector='OR'), name='ledgertransaction_actor_unless_system'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='wallet_ledg_account_a28aa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_xof__gt', 0)), name='ledgerentry_amount_positive'),
        ),
    ]
