# Generated by Django 5.2.17 on 2026-10-05 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('wallet', '0003_platform_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_bps', models.PositiveIntegerField(verbose_name='taux (points de base)')),
                ('cap_xof', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='plafond par mission (F CFA)')),
                ('valid_from', models.DateTimeField(verbose_name='en vigueur à partir de')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.trade')),
            ],
            options={
                'verbose_name': 'taux de commission',
                'verbose_name_plural': 'taux de commission',
                'ordering': ('-valid_from',),
                'constraints': [models.UniqueConstraint(fields=('trade', 'valid_from'), name='commissionrate_unique_trade_valid_from', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('rate_bps__lte', 5000)), name='commissionrate_rate_bps_max'), models.CheckConstraint(condition=models.Q(('cap_xof__isnull', True), ('cap_xof__gt', 0), _connector='OR'), name='commissionrate_cap_positive')],
            },
        ),
    ]
