# Generated by Django 5.2.17 on 2026-10-05 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_mediation_cancel_group'),
        ('catalog', '0001_initial'),
        ('providers', '0002_validation_pros_group'),
        ('wallet', '0005_rates_data_and_accounting_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_xof', models.PositiveBigIntegerField()),
                ('rate_bps', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_xof', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount_xof', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('charged', 'Due'), ('exempt', 'Exemptée')], max_length=8)),
                ('exempt_reason', models.CharField(blank=True, choices=[('review_account', 'Compte de revue des stores'), ('zero_rate', 'Taux de 0'), ('zero_amount', 'Montant arrondi à 0'), ('rate_missing', 'Aucun taux applicable')], max_length=16)),
                ('completion_method', models.CharField(blank=True, max_length=7)),
                ('close_reason', models.CharField(max_length=24)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='bookings.booking')),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.ledgertransaction')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='providers.provider')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.commissionrate')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.trade')),
            ],
            options={
                'verbose_name': 'commission',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'created_at'], name='wallet_comm_provide_453cee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'charged'), ('amount_xof__gt', 0), ('ledger_transaction__isnull', False)), models.Q(models.Q(('status', 'charged'), _negated=True), models.Q(('amount_xof__gt', 0), ('ledger_transaction__isnull', False), _negated=True)), _connector='OR'), name='commission_charged_iff_posted'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'exempt'), models.Q(('exempt_reason', ''), _negated=True)), models.Q(models.Q(('status', 'exempt'), _negated=True), ('exempt_reason', '')), _connector='OR'), name='commission_exempt_has_reason')],
            },
        ),
    ]
