# Generated by Django 5.2.17 on 2026-10-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('providers', '0002_validation_pros_group'),
        ('wallet', '0007_commission_immutable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgeraccount',
            name='ledgeraccount_unique_kind_provider',
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.settlementchannel'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.paymentintent'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('kind', 'provider', 'channel'), name='ledgeraccount_unique_kind_provider_channel', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'platform_collections'), ('channel__isnull', False)), models.Q(models.Q(('kind', 'platform_collections'), _negated=True), models.Q(('channel__isnull', False), _negated=True)), _connector='OR'), name='ledgeraccount_channel_iff_collections'),
        ),
    ]
