# Generated by Django 5.2.17 on 2026-10-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_channel_and_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'ordering': ('-created_at',), 'permissions': [('adjust_ledger', 'Comptabilité : avoirs, gestes commerciaux, corrections et contre-passations')], 'verbose_name': 'transaction du grand livre', 'verbose_name_plural': 'transactions du grand livre'},
        ),
    ]
