# Generated by Django 5.2.17 on 2026-10-05 14:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_validation_pros_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', code='slug_invalid')])),
                ('gateway', models.CharField(choices=[('manual_mobile_money', "Mobile money (déclaré, rapproché par l'Ops)"), ('cash', 'Espèces au bureau'), ('fake', 'Factice (local et test seulement)')], max_length=24)),
                ('label_fr', models.CharField(max_length=60, verbose_name='libellé (fr)')),
                ('label_wo', models.CharField(blank=True, max_length=60, verbose_name='libellé (wo)')),
                ('account_display', models.CharField(blank=True, max_length=60, verbose_name='compte Jeflink affiché')),
                ('instructions_fr', models.TextField(blank=True, max_length=600, verbose_name='instructions (fr)')),
                ('instructions_wo', models.TextField(blank=True, max_length=600, verbose_name='instructions (wo)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'canal de règlement',
                'verbose_name_plural': 'canaux de règlement',
                'ordering': ('position', 'slug'),
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='channel_slug_valid')],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('commission_settlement', 'Règlement de commission')], max_length=24)),
                ('gateway', models.CharField(choices=[('manual_mobile_money', "Mobile money (déclaré, rapproché par l'Ops)"), ('cash', 'Espèces au bureau'), ('fake', 'Factice (local et test seulement)')], max_length=24)),
                ('origin', models.CharField(choices=[('pro_declared', 'Déclaré par le pro'), ('ops_recorded', "Saisi par l'Ops")], max_length=12)),
                ('status', models.CharField(choices=[('declared', 'À rapprocher'), ('needs_correction', 'À corriger par le pro'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('cancelled', 'Retiré par le pro')], max_length=16)),
                ('declared_xof', models.PositiveBigIntegerField()),
                ('received_xof', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payer_last4', models.CharField(blank=True, max_length=4)),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('correction_reason', models.CharField(blank=True, choices=[('reference_not_found', 'Référence introuvable'), ('amount_mismatch', 'Montant différent'), ('paid_at_mismatch', 'Heure différente')], max_length=20)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, choices=[('not_found', 'Introuvable dans le relevé'), ('amount_mismatch', 'Montant différent'), ('duplicate', 'Déjà déclaré'), ('other', 'Autre')], max_length=16)),
                ('decision_note', models.CharField(blank=True, max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='providers.provider')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.settlementchannel')),
            ],
            options={
                'verbose_name': 'intention de paiement',
                'verbose_name_plural': 'intentions de paiement',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_8c3154_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='intent_unique_idempotency_key'), models.UniqueConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), models.Q(('status__in', ('rejected', 'cancelled')), _negated=True)), fields=('channel', 'reference'), name='intent_unique_live_reference'), models.CheckConstraint(condition=models.Q(('declared_xof__gt', 0)), name='intent_declared_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), ('received_xof__gt', 0), ('decided_at__isnull', False)), models.Q(models.Q(('status', 'confirmed'), _negated=True), ('received_xof__isnull', True)), _connector='OR'), name='intent_received_iff_confirmed'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), models.Q(('reject_reason', ''), _negated=True)), models.Q(models.Q(('status', 'rejected'), _negated=True), ('reject_reason', '')), _connector='OR'), name='intent_reject_reason_iff_rejected'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'needs_correction'), _negated=True), models.Q(('correction_reason', ''), _negated=True), _connector='OR'), name='intent_correction_has_reason'), models.CheckConstraint(condition=models.Q(('payer_last4', ''), ('payer_last4__regex', '^[0-9]{4}$'), _connector='OR'), name='intent_payer_last4_digits'), models.CheckConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), models.Q(('receipt_number', ''), _negated=True), _connector='OR'), name='intent_reference_or_receipt')],
            },
        ),
    ]
