# Generated by Django 5.2.17 on 2026-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_accounting_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'ordering': ('created_at',), 'permissions': [('decide_paymentintent', 'Rapprochement : confirmer, renvoyer ou rejeter un règlement, en saisir un')], 'verbose_name': 'intention de paiement', 'verbose_name_plural': 'intentions de paiement'},
        ),
    ]
