# Generated by Django 5.2.17 on 2026-10-05 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_reconciliation_group'),
        ('providers', '0002_validation_pros_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('receipt_number', ''), _negated=True), models.Q(('status__in', ('rejected', 'cancelled')), _negated=True)), fields=('channel', 'receipt_number'), name='intent_unique_live_receipt'),
        ),
    ]
