# Generated by Django 5.2.17 on 2026-10-03 01:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(help_text="Identifiant de l'URL (/plombier/ouakam). Figé après création.", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', code='slug_invalid')])),
                ('name_fr', models.CharField(max_length=60, verbose_name='nom (fr)')),
                ('name_wo', models.CharField(blank=True, max_length=60, verbose_name='nom (wo)')),
                ('short_description_fr', models.CharField(blank=True, max_length=160, verbose_name='description courte (fr)')),
                ('short_description_wo', models.CharField(blank=True, max_length=160, verbose_name='description courte (wo)')),
                ('seo_title_fr', models.CharField(blank=True, help_text='H1 et titre de page ; sinon le nom.', max_length=70, verbose_name='titre SEO (fr)')),
                ('seo_title_wo', models.CharField(blank=True, max_length=70, verbose_name='titre SEO (wo)')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Séparés par des virgules : « frigoriste, clim ».', size=None)),
                ('icon_key', models.CharField(blank=True, max_length=40, verbose_name='pictogramme')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'métier',
                'ordering': ('position', 'name_fr'),
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='trade_slug_format'), models.CheckConstraint(condition=models.Q(('name_fr', ''), _negated=True), name='trade_name_fr_required')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', code='slug_invalid')])),
                ('name_fr', models.CharField(max_length=80, verbose_name='nom (fr)')),
                ('name_wo', models.CharField(blank=True, max_length=80, verbose_name='nom (wo)')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Séparés par des virgules : « frigoriste, clim ».', size=None)),
                ('price_from_xof', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='à partir de (XOF)')),
                ('urgent', models.BooleanField(default=False, help_text='Fuite, panne de courant, frigo en panne.')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('position', models.PositiveSmallIntegerField(default=100)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.trade')),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ('position', 'name_fr'),
                'constraints': [models.UniqueConstraint(fields=('trade', 'slug'), name='service_slug_unique_per_trade'), models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='service_slug_format'), models.CheckConstraint(condition=models.Q(('name_fr', ''), _negated=True), name='service_name_fr_required')],
            },
        ),
    ]
