# Generated by Django 5.2.17 on 2026-10-03 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_validation_pros_group'),
        ('requests', '0003_quotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Acceptée, en attente du pro'), ('scheduled', 'Planifiée'), ('en_route', 'Pro en route'), ('on_site', 'Pro sur place'), ('in_progress', 'Intervention en cours'), ('completed', 'Terminée'), ('disputed', 'Contestée'), ('closed', 'Clôturée'), ('cancelled', 'Annulée')], default='accepted', max_length=12)),
                ('amount_xof', models.PositiveBigIntegerField()),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('confirm_deadline', models.DateTimeField()),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('pro', 'Pro'), ('system', 'Système'), ('ops', 'Équipe Jeflink')], max_length=6)),
                ('cancel_reason', models.CharField(blank=True, max_length=24)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.provider')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='requests.quote')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='requests.servicerequest')),
            ],
            options={
                'verbose_name': 'réservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('actor_kind', models.CharField(choices=[('client', 'Client'), ('pro', 'Pro'), ('system', 'Système'), ('ops', 'Équipe Jeflink')], max_length=6)),
                ('reason', models.CharField(blank=True, max_length=24)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bookings.booking')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'confirm_deadline'], name='bookings_bo_status_b1022c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_bo_client__09b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status'], name='bookings_bo_provide_c56754_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('request',), name='booking_one_active_per_request'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('amount_xof__gt', 0)), name='booking_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('slot_end__gt', models.F('slot_start'))), name='booking_slot_ordered'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_by', ''), _negated=True), _connector='OR'), name='booking_cancelled_has_author'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_d5ff0d_idx'),
        ),
    ]
