# Generated by Django 5.2.17 on 2026-10-03 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_progress_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show_check_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NoShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de contestation'), ('contested', 'Contesté par le pro'), ('confirmed', 'Confirmé'), ('dismissed', 'Écarté')], default='pending', max_length=9)),
                ('contest_note', models.CharField(blank=True, max_length=200)),
                ('contested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='no_show', to='bookings.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'no-show',
                'ordering': ('-created_at',),
                'permissions': [('decide_noshowreport', 'Médiation : trancher un no-show')],
                'indexes': [models.Index(fields=['status', 'created_at'], name='bookings_no_status_7f84f9_idx')],
            },
        ),
    ]
