# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_completion_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('before', 'Avant'), ('after', 'Après')], max_length=6)),
                ('status', models.CharField(choices=[('processing', 'Miniature en cours'), ('ready', 'Prête'), ('failed', 'En échec')], default='processing', max_length=10)),
                ('image_key', models.CharField(blank=True, max_length=120)),
                ('thumb_key', models.CharField(blank=True, max_length=120)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='bookings.booking')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['booking', 'phase'], name='bookings_bo_booking_5b5a9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'idempotency_key'), name='bookingphoto_idempotency')],
            },
        ),
    ]
