# Generated by Django 5.2.17 on 2026-10-03 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('withdrawn', 'Retiré'), ('lapsed', 'Caduc')], default='proposed', max_length=9)),
                ('reason', models.CharField(choices=[('visit_diagnosis', 'Diagnostic sur place'), ('extra_work', 'Travail en plus'), ('parts', 'Pièces'), ('other', 'Autre')], max_length=15)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('previous_amount_xof', models.PositiveBigIntegerField()),
                ('total_xof', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'avenant',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AmendmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=6)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('amount_xof', models.PositiveBigIntegerField()),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bookings.amendment')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='amendment',
            constraint=models.UniqueConstraint(fields=('booking', 'idempotency_key'), name='amendment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='amendment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('booking',), name='amendment_one_proposed_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='amendment',
            constraint=models.CheckConstraint(condition=models.Q(('total_xof__gt', 0), ('previous_amount_xof__gt', 0)), name='amendment_amounts_positive'),
        ),
        migrations.AddConstraint(
            model_name='amendment',
            constraint=models.CheckConstraint(condition=models.Q(('total_xof', models.F('previous_amount_xof')), _negated=True), name='amendment_changes_the_price'),
        ),
        migrations.AddConstraint(
            model_name='amendmentline',
            constraint=models.UniqueConstraint(fields=('amendment', 'position'), name='amendmentline_position'),
        ),
        migrations.AddConstraint(
            model_name='amendmentline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_xof__gt', 0)), name='amendmentline_amount_positive'),
        ),
    ]
