# Generated by Django 5.2.17 on 2026-10-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_amendments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingphoto',
            options={'ordering': ('created_at', 'id'), 'permissions': [('restore_bookingphoto', 'Médiation : réafficher une photo signalée')], 'verbose_name': 'photo'},
        ),
    ]
