# Generated by Django 5.2.17 on 2026-10-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_mediation_group_disputes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at',), 'permissions': [('cancel_booking_ops', 'Médiation : annuler une mission bloquée')], 'verbose_name': 'réservation'},
        ),
        migrations.AddField(
            model_name='booking',
            name='stuck_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
